# Generated by Django 4.0.6 on 2022-07-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='rent',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='sale',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
