# Generated by Django 4.0.6 on 2022-07-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_state_rent_state_sale_alter_state_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
