# Generated by Django 4.0.6 on 2022-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_state_rentmode_state_rentprice_alter_state_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='address',
            field=models.CharField(default='Ejemplo 123', max_length=50),
        ),
        migrations.AddField(
            model_name='state',
            name='postCode',
            field=models.IntegerField(default=2000),
        ),
    ]
