# Generated by Django 4.0.6 on 2022-07-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_state_date_state_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='type',
            field=models.CharField(default='Otra', max_length=25),
        ),
    ]
