# Generated by Django 4.0.6 on 2022-07-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_state_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
